# Beep feel better
print("\nThank you for saving me! I am Beep and I am a robot. What is your name?")
print()
name = input()
print(f"\t\tNice to meet you {name}!")
print("\n\tAs a reward, I would like to show you one of my tricks.")
print("For any number you choose from 1 to 10, if you follow 4 math operations, the result will be always 3")
print("\nThe operations will be:\n1 to duplicate it,\n2 then to add 6,\n3 to divide the result by 2,\n4 and finally, to  subtract from this your number")
print("\nLet's try! Think to a number:")
print()
number = int(input())
print(f"\nDuplicating it, you should have {number*2}.")
print(f"Now, adding 6 to it and then dividing by 2, will be {((number*2)+6)/2}.")
print("At last, now take from it the number you have initially though.")
print(f"\t\t\t Hurrey! It is {((number*2)+6)/2-number}!!! 👨")
print("\nDid you like my trick? How many stars will you give me?")
stars = int(input())
print(f"Well, these beautiful flowers are for you: {stars*'🌻'}. Have a lovely day! Beep 😜")


